Tienda/config/routes.rb
Tienda::Application.routes.draw do
  resources :cliente_productos

  resources :productos

  resources :clientes

end

Tienda/app/models/Cliente_Producto.rb
class ClienteProducto < ActiveRecord::Base
	belongs_to :cliente
	belongs_to :producto

end

Tienda/app/models/cliente.rb
class Cliente < ActiveRecord::Base

has_many :Cliente_Producto
  has_many :productos, :through => :Cliente_Producto
end

Tienda/app/models/producto.rb
class Producto < ActiveRecord::Base
end

Tienda/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Tienda/app/controllers/cliente_productos_controller.rb
class ClienteProductosController < ApplicationController
  # GET /cliente_productos
  # GET /cliente_productos.json
  def index
    @cliente_productos = ClienteProducto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cliente_productos }
    end
  end

  # GET /cliente_productos/1
  # GET /cliente_productos/1.json
  def show
    @cliente_producto = ClienteProducto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente_producto }
    end
  end

  # GET /cliente_productos/new
  # GET /cliente_productos/new.json
  def new
    @cliente_producto = ClienteProducto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente_producto }
    end
  end

  # GET /cliente_productos/1/edit
  def edit
    @cliente_producto = ClienteProducto.find(params[:id])
  end

  # POST /cliente_productos
  # POST /cliente_productos.json
  def create
    @cliente_producto = ClienteProducto.new(params[:cliente_producto])

    respond_to do |format|
      if @cliente_producto.save
        format.html { redirect_to @cliente_producto, notice: 'Cliente producto was successfully created.' }
        format.json { render json: @cliente_producto, status: :created, location: @cliente_producto }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cliente_productos/1
  # PUT /cliente_productos/1.json
  def update
    @cliente_producto = ClienteProducto.find(params[:id])

    respond_to do |format|
      if @cliente_producto.update_attributes(params[:cliente_producto])
        format.html { redirect_to @cliente_producto, notice: 'Cliente producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cliente_productos/1
  # DELETE /cliente_productos/1.json
  def destroy
    @cliente_producto = ClienteProducto.find(params[:id])
    @cliente_producto.destroy

    respond_to do |format|
      format.html { redirect_to cliente_productos_url }
      format.json { head :no_content }
    end
  end
end

Tienda/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

Tienda/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])

    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
end

Tienda/app/helpers/application_helper.rb
module ApplicationHelper
end

Tienda/app/helpers/cliente_productos_helper.rb
module ClienteProductosHelper
end

Tienda/app/helpers/clientes_helper.rb
module ClientesHelper
end

Tienda/app/helpers/productos_helper.rb
module ProductosHelper
end

Tienda/app/views/cliente_productos/_form.html.erb
<%= form_for(@cliente_producto) do |f| %>
  <% if @cliente_producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente_producto.errors.count, "error") %> prohibited this cliente_producto from being saved:</h2>

      <ul>
      <% @cliente_producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cod %><br />
    <%= f.number_field :cod %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Tienda/app/views/cliente_productos/edit.html.erb
<h1>Editing cliente_producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente_producto %> |
<%= link_to 'Back', cliente_productos_path %>

Tienda/app/views/cliente_productos/index.html.erb
<h1>Listing cliente_productos</h1>

<table>
  <tr>
    <th>Cod</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cliente_productos.each do |cliente_producto| %>
  <tr>
    <td><%= cliente_producto.cod %></td>
    <td><%= link_to 'Show', cliente_producto %></td>
    <td><%= link_to 'Edit', edit_cliente_producto_path(cliente_producto) %></td>
    <td><%= link_to 'Destroy', cliente_producto, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente producto', new_cliente_producto_path %>

Tienda/app/views/cliente_productos/new.html.erb
<h1>New cliente_producto</h1>

<%= render 'form' %>

<%= link_to 'Back', cliente_productos_path %>

Tienda/app/views/cliente_productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cod:</b>
  <%= @cliente_producto.cod %>
</p>


<%= link_to 'Edit', edit_cliente_producto_path(@cliente_producto) %> |
<%= link_to 'Back', cliente_productos_path %>

Tienda/app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :num_tarjeta %><br />
    <%= f.text_field :num_tarjeta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Tienda/app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

Tienda/app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Apellido</th>
    <th>Num tarjeta</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.name %></td>
    <td><%= cliente.apellido %></td>
    <td><%= cliente.num_tarjeta %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

Tienda/app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

Tienda/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cliente.name %>
</p>

<p>
  <b>Apellido:</b>
  <%= @cliente.apellido %>
</p>

<p>
  <b>Num tarjeta:</b>
  <%= @cliente.num_tarjeta %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

Tienda/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tienda</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Tienda/app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.number_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.number_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Tienda/app/views/productos/edit.html.erb
<h1>Editing producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

Tienda/app/views/productos/index.html.erb
<h1>Listing productos</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Descripcion</th>
    <th>Precio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @productos.each do |producto| %>
  <tr>
    <td><%= producto.codigo %></td>
    <td><%= producto.descripcion %></td>
    <td><%= producto.precio %></td>
    <td><%= link_to 'Show', producto %></td>
    <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
    <td><%= link_to 'Destroy', producto, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Producto', new_producto_path %>

Tienda/app/views/productos/new.html.erb
<h1>New producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

Tienda/app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @producto.codigo %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @producto.descripcion %>
</p>

<p>
  <b>Precio:</b>
  <%= @producto.precio %>
</p>


<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>